Repository PreferredAI/cornac, pull requests merged in 2024-03, with the labels that each got.

#595 Enhance serving evaluation endpoints
  cornac/serving/app.py
  tests/cornac/serving/test_app.py
Labels: feature

#599 Update docker-compose serving image
  docker-compose.yml
Labels: maintenance

#601 Update to announcement banner in readthedocs
  docs/announcement.html
Labels: docs

#598 [docs] Update link in working_with_auxiliary_data.md
  tutorials/working_with_auxiliary_data.md
Labels: docs

#600 Hypergraphs with Attention on Reviews for Explainable Recommendation
  .gitignore
  README.md
  cornac/models/__init__.py
  cornac/models/hypar/__init__.py
  cornac/models/hypar/dgl_utils.py
  cornac/models/hypar/hypar.py
  cornac/models/hypar/lightgcn.py
  cornac/models/hypar/recom_hypar.py
  cornac/models/hypar/requirements.txt
  cornac/models/hypar/requirements_cu116.txt
  docs/source/api_ref/models.rst
Labels: models

#597 Feature/add dmrl: Add DMRL Model
  README.md
  cornac/models/__init__.py
  cornac/models/dmrl/__init__.py
  cornac/models/dmrl/d_cor_calc.py
  cornac/models/dmrl/dmrl.py
  cornac/models/dmrl/pwlearning_sampler.py
  cornac/models/dmrl/recom_dmrl.py
  cornac/models/dmrl/requirements.txt
  cornac/models/dmrl/transformer_text.py
  cornac/models/dmrl/transformer_vision.py
  docs/source/api_ref/models.rst
  examples/README.md
  examples/dmrl_clothes_example.py
  examples/dmrl_example.py
  pytest.ini
  tests/cornac/models/__init__.py
  tests/cornac/models/dmrl/__init__.py
  tests/cornac/models/dmrl/test_distance_calc.py
  tests/cornac/models/dmrl/test_pwlearning_sampler.py
  tests/cornac/models/dmrl/test_transformertext.py
  tests/cornac/models/dmrl/test_transformervision.py
Labels: models

#606 Lightgcn fix
  cornac/models/lightgcn/lightgcn.py
Labels: bug

#608 Add save and load functions for BiVAECF model
  cornac/models/bivaecf/recom_bivaecf.py
Labels: bug

#607 Add metadata file when saving model
  cornac/models/recommender.py
Labels: feature

#610 Improve the main models table and example/tutorials in README
  README.md
Labels: docs
