Repository PreferredAI/cornac, pull requests merged in 2024-01, with the labels that each got.

#574 Add Session-based Recommendations With Recurrent Neural Networks (GRU4Rec) model
  README.md
  cornac/models/__init__.py
  cornac/models/gru4rec/__init__.py
  cornac/models/gru4rec/gru4rec.py
  cornac/models/gru4rec/recom_gru4rec.py
  cornac/models/gru4rec/requirements.txt
  docs/source/api_ref/models.rst
  examples/README.md
  examples/gru4rec_yoochoose.py
Labels: feature, models

#573 Add back Circle CI for publishing code coverage
  .circleci/config.yml
Labels: maintenance

#586 Add Deep Neural Network for Temporal Sets Prediction (DNNTSP) Model
  README.md
  cornac/models/__init__.py
  cornac/models/dnntsp/__init__.py
  cornac/models/dnntsp/dnntsp.py
  cornac/models/dnntsp/recom_dnntsp.py
  cornac/models/dnntsp/requirements.txt
  docs/source/api_ref/models.rst
  examples/README.md
  examples/dnntsp_tafeng.py
Labels: models

#591 [Beacon] max_seq_length is the maximum number of baskets in training sequence
  cornac/models/beacon/recom_beacon.py
Labels: bug

#588 Add column model type into table models
  README.md
Labels: feature
